/**
 * menu-system.js
 * Fully dynamic navigation system pulling from site registry
 */
"use strict";

document.addEventListener("DOMContentLoaded", () => {
    const navDock = document.getElementById('master-nav-dock');
    if (!navDock) return;

    // 1. Configuration & Label Mapping
    // Map your folder names to human-readable labels
    const CATEGORY_MAP = {
        'root': 'Home',
        'guide': 'Legal Guides',
        'lawyer': 'Attorneys',
        'location': 'Locations',
        'bad-faith': 'Bad Faith',
        'settlement': 'Settlements',
        'calculator': 'Tools'
    };

    // Define the order you want them to appear in the menu
    const MENU_ORDER = ['root', 'lawyer', 'guide', 'bad-faith', 'location', 'calculator'];

    // 2. Data Retrieval from window.pageRegistry (generated by generate-files.js)
    const registry = window.pageRegistry || [];

    /**
     * Finds the primary index URL for a specific folder category
     */
    const getCategoryUrl = (slug) => {
        if (slug === 'root') {
            const root = registry.find(p => p.path === 'index.html');
            return root ? root.url : '/';
        }
        // Find the index.html within that specific folder
        const folderIndex = registry.find(p => p.path === `${slug}/index.html`);
        // Fallback to the first page in that folder if no index exists
        const anyFolderPage = registry.find(p => p.path.startsWith(`${slug}/`));
        
        return folderIndex ? folderIndex.url : (anyFolderPage ? anyFolderPage.url : `#${slug}`);
    };

    // 3. Generate Navigation Links HTML
    const desktopLinks = MENU_ORDER.map(slug => `
        <a href="${getCategoryUrl(slug)}" class="text-sm font-semibold text-gray-700 hover:text-emerald-700 transition-colors duration-200">
            ${CATEGORY_MAP[slug]}
        </a>
    `).join('');

    const mobileLinks = MENU_ORDER.map(slug => `
        <a href="${getCategoryUrl(slug)}" class="block py-2 text-base font-semibold text-gray-800 hover:text-emerald-700 border-b border-gray-50 last:border-0">
            ${CATEGORY_MAP[slug]}
        </a>
    `).join('');

    // 4. Construct Final HTML Structure (McKinsey Style UI)
    const menuHTML = `
        <!-- Desktop Menu -->
        <nav class="hidden lg:flex items-center space-x-8 mr-6" aria-label="Main Navigation">
            ${desktopLinks}
            <a href="tel:+19045009653" class="inline-flex items-center px-5 py-2.5 bg-emerald-700 text-white text-sm font-bold rounded-md shadow-sm hover:bg-emerald-800 hover:shadow-md transition-all duration-200">
                Free Case Review
            </a>
        </nav>
        
        <!-- Mobile Toggle -->
        <button id="mobile-menu-btn" class="lg:hidden flex items-center p-2 text-gray-700 hover:text-emerald-700 focus:outline-none" aria-expanded="false" aria-label="Toggle menu">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path id="menu-icon" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
        </button>

        <!-- Mobile Dropdown Container -->
        <div id="mobile-menu-dropdown" class="hidden absolute top-full left-0 w-full bg-white shadow-2xl z-50 border-t border-gray-100 p-6 space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">
            <div class="flex flex-col space-y-2">
                ${mobileLinks}
            </div>
            <div class="pt-4 mt-2">
                <a href="tel:+19045009653" class="flex items-center justify-center w-full px-6 py-4 bg-violet-700 text-white text-base font-bold rounded-lg shadow-lg">
                    Call (904) 500-9653
                </a>
            </div>
        </div>
    `;

    // 5. Injection & Interaction Logic
    navDock.innerHTML = menuHTML;
    
    const header = navDock.closest('header');
    if(header) {
        header.classList.add('sticky', 'top-0', 'z-50', 'bg-white/95', 'backdrop-blur-md', 'border-b', 'border-gray-200');
    }

    const toggleBtn = document.getElementById('mobile-menu-btn');
    const dropdown = document.getElementById('mobile-menu-dropdown');
    const menuPath = document.getElementById('menu-icon');
    
    toggleBtn.addEventListener('click', () => {
        const isHidden = dropdown.classList.toggle('hidden');
        toggleBtn.setAttribute('aria-expanded', !isHidden);
        
        // Toggle Icon between Hamburger and Close (X)
        if (isHidden) {
            menuPath.setAttribute('d', 'M4 6h16M4 12h16M4 18h16');
        } else {
            menuPath.setAttribute('d', 'M6 18L18 6M6 6l12 12');
        }
    });

    // Close mobile menu on outside click
    document.addEventListener('click', (e) => {
        if (!navDock.contains(e.target) && !dropdown.classList.contains('hidden')) {
            dropdown.classList.add('hidden');
            menuPath.setAttribute('d', 'M4 6h16M4 12h16M4 18h16');
        }
    });
});
